# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  # Local only podspec will download source zip
  pod 'AMapSearch-NO-IDFA-XC', :path => '../'
#  pod 'AMapSearch-NO-IDFA-XC', :podspec => '../'


end
